# Generated by Django 2.0.5 on 2018-05-16 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bims', '0004_biologicalcollectionrecord_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv/')),
            ],
            options={
                'verbose_name': 'CSV Document',
                'verbose_name_plural': 'CSV Documents',
            },
        ),
        migrations.CreateModel(
            name='FishCollectionRecord',
            fields=[
                ('biologicalcollectionrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bims.BiologicalCollectionRecord')),
                ('habitat', models.CharField(blank=True, choices=[('euryhaline', 'Euryhaline'), ('freshwater', 'Freshwater')], max_length=50)),
            ],
            options={
                'verbose_name': 'fish',
                'verbose_name_plural': 'fishes',
            },
            bases=('bims.biologicalcollectionrecord',),
        ),
    ]
