# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='depth_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='do',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='ec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='near_bed_velocity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='nutrients',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='substrate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='temp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='turbidity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
