# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0087_merge_20181206_0607'),
        ('fish', '0003_auto_20181001_0351'),
        ('healthyrivers_base', '0002_migrate_fish_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishcollectionrecord',
            name=b'biologicalcollectionrecord_ptr',
        ),
        migrations.DeleteModel(
            name='FishCollectionRecord',
        ),
    ]
